[package]
name = "history-box"
version = "0.1.1"
description = "A history box that keeps history references"
edition = "2021"
license = "MIT"
repository = "https://github.com/victorteokw/history-box"

[dependencies]
